baseURL = "https://eodavis2.netlify.app"
title = "Elizabeth Oneita Davis"
author = ""
copyright = "Copyright © 2020"
languageCode = "en"
DefaultContentLanguage = "en"
hasCJKLanguage=true
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
disqusShortname = "YOURSHORTNAME"
googleAnalytics = "UA-FAKE"
theme = "hugo-theme-tokiwa"

[permalinks]
    post = "/:slug/"

[markup.goldmark.renderer]
unsafe= true

[params]
description = """
A site for R materials.
"""
favicon = "img/favicon-32x32.png"
math = true # for introducing $KaTEX$
env = "production" # for Google Analytics and DISQUS.
useChineseFonts = true
bannerFont = "fonts/exampleFont"

[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "Posts"
    weight = 1
    identifier = "post"
    url = "/post/"
    
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "About"
    weight = 3
    identifier = "about"
    url = "/about/"


[taxonomies]
category = "categories"
tag = "tags"
series = "series"
[social]
instagram="http://https://www.instagram.com/eo_davis/"
twitter="http://twitter.com/__EODavis/"
github="http://https://github.com/EOneita"
researchgate="http://www.researchgate.net/profile/Elizabeth_Davis13"
googlescholar="http://scholar.google.com/citations?hl=en&user=mArHjX4AAAAJ"
# any icon in layouts/partials/svg can be used by the name without the "-line.svg"
