[build]
  command = "hugo --gc --minify -b $https://eodavis2.netlify.app"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.69.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $https://eodavis2.netlify.app"

[context.branch-deploy]
  command = "hugo --gc --minify -b $https://eodavis2.netlify.app"