---
title: Making this Blog
author: E.O. Davis
date: '2020-06-25'
slug: making-this-blog
categories:
  - hugo
  - blogdown
  - gahhhh
tags: []
description: 'The painful road towards enlightenment.'
---

## How this began

In my first blog endeavor I used the incredibly easy `distill` from the people at R Studio, thanks to an incredibly clear step-by-step process dodcumented by [Shamindra Shrotriya](https://www.shamindras.com/posts/2019-07-11-shrotriya2019distillpt1/) (thanks Shamindra!). It was almost impossible to mess up and I'm pretty sure I DIDN'T mess it up when I first did it.

\
Then I forgot about it for a long time, until I made some new R slides for a mini workshop with some colleagues, and wanted to host them somewhere. I found going back to the blog painful and difficult. I now know that was because I had forgotten everything about `distill`'s structure, so if I had been thoughtful/looked at documentation I probably (hopefully) could have figured it out. As it was, I decided to take the opportunity to start from scratch and finally delve into Hugo and blogdown, and on the way finally get accustomed to CSS and HTML. ^[I won't go into getting Hugo and blogdown up and running since many others have done that already. I particularly recommend Alison Hill's [post](https://alison.rbind.io/post/2017-06-12-up-and-running-with-blogdown/)].

\
So, what theme did I choose out the gate? Of course I chose one that is [beautiful](https://github.com/heyeshuang/hugo-theme-tokiwa/tree/master/exampleSite) but leans heavily into Javascript and not even normal CSS, but CSS add-ons. Not only that, but it has a very "unique" directory structure that definitely didn't correspond to what I vaguely remembered from `distill`. And finally, the little icons you can see below/in the bottom left only had the popular "social" icons pre-loaded, whereas I'm a boring scientist who needs boring scientist ones. 

\
This may not sound like a big deal, but it WAS. What followed was an approximately 6 hour saga of me overcoming the following hurdles:

1) How the icons populate according to this theme (there is a folder called `svg` that all the little icons live in and some HTML code within the "social" partial that tells the site what to do with those icons, i.e. make them pretty and adapted to the CSS).
2) How to get an svg icon (turned out it's as simple as using a free conversion platform for .pngs).
3) Whoaaaa this icon is enormous and coming up with bonkers text, as well???
\
  *-> This is where I realized I could open .svgs within R Studio*
  \
  *-> At the same time, this is where I realized that I didn't understand .svgs.*
4) I compared my crazy .svgs with the ones pre-loaded into the Tokiwa theme and after more Googling than was probably necessary for something ultimately so simple, I discovered that I could readjust the size pretty easily and also easily remove all the random text.
5) Finally, I discovered that I could change the color of the icon *within the .svg itself*. Magic!

## Directory issues
Great! I tortorously figured out something super simple. Now it was time to start migrating over all of my previous blog's content. My posts were set up by `distill` into separate folders that had their own "static" attributes. Instantly, this was a stumbling block. Hugo manages their directories completely differently, and although I felt like I understood the Hugo structure in theory, I couldn't for the life of me figure out where on earth my images were supposed to go to end up in my posts. I tried sticking them everywhere and ended up breaking the theme (but at least I now knew ONE place the images weren't supposed to go!).

In the end, it wouldn't show up in my R Markdown post (as in, .Rmd claimed there was no image at the path I specified), but WOULD show up in actual rendering of the post. Weird. Somebody significantly more skilled than me can untangle that odd situation.

Now I was having issues with links. Trying to link to `xaringan` slides was completely broken, and I couldn't quite figure out why.